<?php
namespace Midi\Koala\Replaying;

/**
 * Autogenerated by Disf-CodeGen (0.1.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */    

/** 
    * @property int ActionIndex 
    * @property string Request 
    * @property int OccurredAt 
    * @property int ResponseTime 
    * @property \Midi\Koala\Replaying\Peer Peer
    * @property string ActionType 
    * @property string Response 
*/ 
class CallOutbound extends \ArrayObject {

    public static $SCHEMA = array(
        'disfSchemaFormatVersion' => 1003,
        'isUnion' => false,
        'classObject' => CallOutbound::class,
        'className' => 'Midi\Koala\Replaying\CallOutbound',
        'annotations' => array(),
        'fields' => array(
            "ActionIndex" => array(
                "fieldId" => 1,
                "thriftType" => 'I64',
                "isRequired" => False,
                "annotations" => array(),
            ),
            "OccurredAt" => array(
                "fieldId" => 2,
                "thriftType" => 'I64',
                "isRequired" => False,
                "annotations" => array(),
            ),
            "ActionType" => array(
                "fieldId" => 3,
                "thriftType" => 'STRING',
                "isRequired" => False,
                "annotations" => array(),
            ),
            "Peer" => array(
                "fieldId" => 4,
                "thriftType" => 'STRUCT',
                "isRequired" => False,
                "annotations" => array(),
                "classObject" => \Midi\Koala\Replaying\Peer::class,
            ),
            "Request" => array(
                "fieldId" => 5,
                "thriftType" => 'STRING',
                "isRequired" => False,
                "annotations" => array(),
            ),
            "ResponseTime" => array(
                "fieldId" => 6,
                "thriftType" => 'I64',
                "isRequired" => False,
                "annotations" => array(),
            ),
            "Response" => array(
                "fieldId" => 7,
                "thriftType" => 'STRING',
                "isRequired" => False,
                "annotations" => array(),
            ),
            "SocketFD" => array(
                "fieldId" => 8,
                "thriftType" => 'I64',
                "isRequired" => False,
                "annotations" => array(),
            ),
        ),
    );

    public function __construct($array = null) 
    {
        if (!isset($array)) { 
            parent::__construct(array(), \ArrayObject::ARRAY_AS_PROPS);
            return;
        }

        parent::__construct($array, \ArrayObject::ARRAY_AS_PROPS); 

        if(isset($array["ActionIndex"])) { 
            $this->setActionIndex($array["ActionIndex"]);
        }

        if(isset($array["Request"])) { 
            $this->setRequest($array["Request"]);
        }

        if(isset($array["OccurredAt"])) { 
            $this->setOccurredAt($array["OccurredAt"]);
        }

        if(isset($array["ResponseTime"])) { 
            $this->setResponseTime($array["ResponseTime"]);
        }

        if(isset($array["Peer"])) { 
            $this->setPeer($array["Peer"]);
        }

        if(isset($array["ActionType"])) { 
            $this->setActionType($array["ActionType"]);
        }

        if(isset($array["Response"])) { 
            $this->setResponse($array["Response"]);
        }

        if(isset($array["SocketFD"])) {
            $this->setSocketFD($array["SocketFD"]);
        }

    }

    /** 
     * @return int 
    */ 
    public function getActionIndex()/* : int */ {
        return \Midi\Koala\Common\TypeConverter::to_int($this["ActionIndex"]);
    }

    /** 
     * @param int $val 
    */ 
    public function setActionIndex(/* int */ $val) {
        $this["ActionIndex"] = \Midi\Koala\Common\TypeConverter::to_int($val);
    }

    /** 
     * @return string 
    */ 
    public function getRequest()/* : string */ {
        return \Midi\Koala\Common\TypeConverter::to_string($this["Request"]);
    }

    /** 
     * @param string $val 
    */ 
    public function setRequest(/* string */ $val) {
        $this["Request"] = \Midi\Koala\Common\TypeConverter::to_string($val);
    }

    /** 
     * @return int 
    */ 
    public function getOccurredAt()/* : int */ {
        return \Midi\Koala\Common\TypeConverter::to_int($this["OccurredAt"]);
    }

    /** 
     * @param int $val 
    */ 
    public function setOccurredAt(/* int */ $val) {
        $this["OccurredAt"] = \Midi\Koala\Common\TypeConverter::to_int($val);
    }

    /** 
     * @return int 
    */ 
    public function getResponseTime()/* : int */ {
        return \Midi\Koala\Common\TypeConverter::to_int($this["ResponseTime"]);
    }

    /** 
     * @param int $val 
    */ 
    public function setResponseTime(/* int */ $val) {
        $this["ResponseTime"] = \Midi\Koala\Common\TypeConverter::to_int($val);
    }

    /** 
     * @return \Midi\Koala\Replaying\Peer
    */ 
    public function getPeer()/* : \Midi\Koala\Replaying\Peer */ {
        return \Midi\Koala\Common\TypeConverter::to_struct($this["Peer"], \Midi\Koala\Replaying\Peer::class);
    }

    /** 
     * @param \Midi\Koala\Replaying\Peer $val
    */ 
    public function setPeer(/* \Midi\Koala\Replaying\Peer */ $val) {
        $this["Peer"] = \Midi\Koala\Common\TypeConverter::to_struct($val, \Midi\Koala\Replaying\Peer::class);
    }

    /** 
     * @return string 
    */ 
    public function getActionType()/* : string */ {
        return \Midi\Koala\Common\TypeConverter::to_string($this["ActionType"]);
    }

    /** 
     * @param string $val 
    */ 
    public function setActionType(/* string */ $val) {
        $this["ActionType"] = \Midi\Koala\Common\TypeConverter::to_string($val);
    }

    /** 
     * @return string 
    */ 
    public function getResponse()/* : string */ {
        return \Midi\Koala\Common\TypeConverter::to_string($this["Response"]);
    }

    /** 
     * @param string $val 
    */ 
    public function setResponse(/* string */ $val) {
        $this["Response"] = \Midi\Koala\Common\TypeConverter::to_string($val);
    }

    /**
     * @return int
     */
    public function getSocketFD()/* : int */ {
        return \Midi\Koala\Common\TypeConverter::to_int($this["SocketFD"]);
    }

    /**
     * @param int $val
     */
    public function setSocketFD(/* int */ $val) {
        $this["SocketFD"] = \Midi\Koala\Common\TypeConverter::to_int($val);
    }

}

/* THRIFT IDL
namespace php koala.replaying
include "Peer.thrift"

struct CallOutbound {
    1: i64 ActionIndex
    2: i64 OccurredAt
    3: string ActionType
    4: Peer.Peer Peer
    5: binary Request
    6: i64 ResponseTime
    7: binary Response
    8: i64 SocketFD
}
*/