<?php
namespace Midi\Koala\Replaying;

/**
 * Autogenerated by Disf-CodeGen (0.1.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */    

/** 
    * @property \Midi\Koala\Replaying\Peer Peer
    * @property int ActionIndex 
    * @property string Request 
    * @property int OccurredAt 
    * @property string ActionType 
*/ 
class CallFromInbound extends \ArrayObject {

    public static $SCHEMA = array( 
        'disfSchemaFormatVersion' => 1003,
        'isUnion' => false,
        'classObject' => CallFromInbound::class,
        'className' => 'Midi\Koala\Replaying\CallFromInbound',
        'annotations' => array(),
        'fields' => array(
            "ActionIndex" => array(
                "fieldId" => 1, 
                "thriftType" => 'I64',
                "isRequired" => False,
                "annotations" => array(),
            ),
            "OccurredAt" => array(
                "fieldId" => 2, 
                "thriftType" => 'I64',
                "isRequired" => False,
                "annotations" => array(),
            ),
            "ActionType" => array(
                "fieldId" => 3, 
                "thriftType" => 'STRING',
                "isRequired" => False,
                "annotations" => array(),
            ),
            "Peer" => array(
                "fieldId" => 4, 
                "thriftType" => 'STRUCT',
                "isRequired" => False,
                "annotations" => array(),
                "classObject" => \Midi\Koala\Replaying\Peer::class,
            ),
            "Request" => array(
                "fieldId" => 5, 
                "thriftType" => 'STRING',
                "isRequired" => False,
                "annotations" => array(),
            ),
        ),
    );

    public function __construct($array = null) 
    {
        if (!isset($array)) { 
            parent::__construct(array(), \ArrayObject::ARRAY_AS_PROPS);
            return;
        }

        parent::__construct($array, \ArrayObject::ARRAY_AS_PROPS); 

        if(isset($array["Peer"])) { 
            $this->setPeer($array["Peer"]);
        }

        if(isset($array["ActionIndex"])) { 
            $this->setActionIndex($array["ActionIndex"]);
        }

        if(isset($array["Request"])) { 
            $this->setRequest($array["Request"]);
        }

        if(isset($array["OccurredAt"])) { 
            $this->setOccurredAt($array["OccurredAt"]);
        }

        if(isset($array["ActionType"])) { 
            $this->setActionType($array["ActionType"]);
        }

    }

    /** 
     * @return \Midi\Koala\Replaying\Peer
    */ 
    public function getPeer()/* : \Midi\Koala\Replaying\Peer */ {
        return \Midi\Koala\Common\TypeConverter::to_struct($this["Peer"], \Midi\Koala\Replaying\Peer::class);
    }

    /** 
     * @param \Midi\Koala\Replaying\Peer $val
    */ 
    public function setPeer(/* \Midi\Koala\Replaying\Peer */ $val) {
        $this["Peer"] = \Midi\Koala\Common\TypeConverter::to_struct($val, \Midi\Koala\Replaying\Peer::class);
    }

    /** 
     * @return int 
    */ 
    public function getActionIndex()/* : int */ {
        return \Midi\Koala\Common\TypeConverter::to_int($this["ActionIndex"]);
    }

    /** 
     * @param int $val 
    */ 
    public function setActionIndex(/* int */ $val) {
        $this["ActionIndex"] = \Midi\Koala\Common\TypeConverter::to_int($val);
    }

    /** 
     * @return string 
    */ 
    public function getRequest()/* : string */ {
        return \Midi\Koala\Common\TypeConverter::to_string($this["Request"]);
    }

    /** 
     * @param string $val 
    */ 
    public function setRequest(/* string */ $val) {
        $this["Request"] = \Midi\Koala\Common\TypeConverter::to_string($val);
    }

    /** 
     * @return int 
    */ 
    public function getOccurredAt()/* : int */ {
        return \Midi\Koala\Common\TypeConverter::to_int($this["OccurredAt"]);
    }

    /** 
     * @param int $val 
    */ 
    public function setOccurredAt(/* int */ $val) {
        $this["OccurredAt"] = \Midi\Koala\Common\TypeConverter::to_int($val);
    }

    /** 
     * @return string 
    */ 
    public function getActionType()/* : string */ {
        return \Midi\Koala\Common\TypeConverter::to_string($this["ActionType"]);
    }

    /** 
     * @param string $val 
    */ 
    public function setActionType(/* string */ $val) {
        $this["ActionType"] = \Midi\Koala\Common\TypeConverter::to_string($val);
    }
}

/* THRIFT IDL
namespace php koala.replaying
include "Peer.thrift"

struct CallFromInbound {
    1: i64 ActionIndex
    2: i64 OccurredAt
    3: string ActionType
    4: Peer.Peer Peer
    5: binary Request
}
*/