<?php
namespace Midi\Koala\Replaying;

/**
 * Autogenerated by Disf-CodeGen (0.1.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */    

/** 
    * @property int ActionIndex 
    * @property int OccurredAt 
    * @property string Response 
    * @property string ActionType 
*/ 
class ReturnInbound extends \ArrayObject {

    public static $SCHEMA = array( 
        'disfSchemaFormatVersion' => 1003,
        'isUnion' => false,
        'classObject' => ReturnInbound::class,
        'className' => 'Midi\Koala\Replaying\ReturnInbound',
        'annotations' => array(),
        'fields' => array(
            "ActionIndex" => array(
                "fieldId" => 1, 
                "thriftType" => 'I64',
                "isRequired" => False,
                "annotations" => array(),
            ),
            "OccurredAt" => array(
                "fieldId" => 2, 
                "thriftType" => 'I64',
                "isRequired" => False,
                "annotations" => array(),
            ),
            "Response" => array(
                "fieldId" => 4, 
                "thriftType" => 'STRING',
                "isRequired" => False,
                "annotations" => array(),
            ),
            "ActionType" => array(
                "fieldId" => 3, 
                "thriftType" => 'STRING',
                "isRequired" => False,
                "annotations" => array(),
            ),
        ),
    );

    public function __construct($array = null) 
    {
        if (!isset($array)) { 
            parent::__construct(array(), \ArrayObject::ARRAY_AS_PROPS);
            return;
        }

        parent::__construct($array, \ArrayObject::ARRAY_AS_PROPS); 

        if(isset($array["ActionIndex"])) { 
            $this->setActionIndex($array["ActionIndex"]);
        }

        if(isset($array["OccurredAt"])) { 
            $this->setOccurredAt($array["OccurredAt"]);
        }

        if(isset($array["Response"])) { 
            $this->setResponse($array["Response"]);
        }

        if(isset($array["ActionType"])) { 
            $this->setActionType($array["ActionType"]);
        }

    }

    /** 
     * @return int 
    */ 
    public function getActionIndex()/* : int */ {
        return \Midi\Koala\Common\TypeConverter::to_int($this["ActionIndex"]);
    }

    /** 
     * @param int $val 
    */ 
    public function setActionIndex(/* int */ $val) {
        $this["ActionIndex"] = \Midi\Koala\Common\TypeConverter::to_int($val);
    }

    /** 
     * @return int 
    */ 
    public function getOccurredAt()/* : int */ {
        return \Midi\Koala\Common\TypeConverter::to_int($this["OccurredAt"]);
    }

    /** 
     * @param int $val 
    */ 
    public function setOccurredAt(/* int */ $val) {
        $this["OccurredAt"] = \Midi\Koala\Common\TypeConverter::to_int($val);
    }

    /** 
     * @return string 
    */ 
    public function getResponse()/* : string */ {
        return \Midi\Koala\Common\TypeConverter::to_string($this["Response"]);
    }

    /** 
     * @param string $val 
    */ 
    public function setResponse(/* string */ $val) {
        $this["Response"] = \Midi\Koala\Common\TypeConverter::to_string($val);
    }

    /** 
     * @return string 
    */ 
    public function getActionType()/* : string */ {
        return \Midi\Koala\Common\TypeConverter::to_string($this["ActionType"]);
    }

    /** 
     * @param string $val 
    */ 
    public function setActionType(/* string */ $val) {
        $this["ActionType"] = \Midi\Koala\Common\TypeConverter::to_string($val);
    }
}

/* THRIFT IDL
namespace php koala.replaying

struct ReturnInbound {
    1: i64 ActionIndex
    2: i64 OccurredAt
    3: string ActionType
    4: binary Response
}
*/