<?php
namespace Midi\Koala\Replayed;

/**
 * Autogenerated by Disf-CodeGen (0.1.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */    

/** 
    * @property int CallIntoLine 
    * @property CallFunctionArg[] Args 
    * @property string FuncName 
    * @property string ActionType 
    * @property string ActionId 
    * @property string CallIntoFile 
    * @property int OccurredAt 
*/ 
class CallFunction extends \ArrayObject {

    public static $SCHEMA = array( 
        'disfSchemaFormatVersion' => 1003,
        'isUnion' => false,
        'classObject' => CallFunction::class,
        'className' => 'Midi\Koala\Replayed\CallFunction',
        'annotations' => array(),
        'fields' => array(
            "CallIntoLine" => array(
                "fieldId" => 5, 
                "thriftType" => 'I64',
                "isRequired" => False,
                "annotations" => array(),
            ),
            "Args" => array(
                "fieldId" => 7, 
                "thriftType" => 'LIST',
                "isRequired" => False,
                "annotations" => array(),
                "classObject" => CallFunctionArg::class, 
            ),
            "FuncName" => array(
                "fieldId" => 6, 
                "thriftType" => 'STRING',
                "isRequired" => False,
                "annotations" => array(),
            ),
            "ActionType" => array(
                "fieldId" => 3, 
                "thriftType" => 'STRING',
                "isRequired" => False,
                "annotations" => array(),
            ),
            "ActionId" => array(
                "fieldId" => 1, 
                "thriftType" => 'STRING',
                "isRequired" => False,
                "annotations" => array(),
            ),
            "CallIntoFile" => array(
                "fieldId" => 4, 
                "thriftType" => 'STRING',
                "isRequired" => False,
                "annotations" => array(),
            ),
            "OccurredAt" => array(
                "fieldId" => 2, 
                "thriftType" => 'I64',
                "isRequired" => False,
                "annotations" => array(),
            ),
        ),
    );

    public function __construct($array = null) 
    {
        if (!isset($array)) { 
            parent::__construct(array(), \ArrayObject::ARRAY_AS_PROPS);
            return;
        }

        parent::__construct($array, \ArrayObject::ARRAY_AS_PROPS); 

        if(isset($array["CallIntoLine"])) { 
            $this->setCallIntoLine($array["CallIntoLine"]);
        }

        if(isset($array["Args"])) { 
            $this->setArgs($array["Args"]);
        }

        if(isset($array["FuncName"])) { 
            $this->setFuncName($array["FuncName"]);
        }

        if(isset($array["ActionType"])) { 
            $this->setActionType($array["ActionType"]);
        }

        if(isset($array["ActionId"])) { 
            $this->setActionId($array["ActionId"]);
        }

        if(isset($array["CallIntoFile"])) { 
            $this->setCallIntoFile($array["CallIntoFile"]);
        }

        if(isset($array["OccurredAt"])) { 
            $this->setOccurredAt($array["OccurredAt"]);
        }

    }

    /** 
     * @return int 
    */ 
    public function getCallIntoLine()/* : int */ {
        return \Midi\Koala\Common\TypeConverter::to_int($this["CallIntoLine"]);
    }

    /** 
     * @param int $val 
    */ 
    public function setCallIntoLine(/* int */ $val) {
        $this["CallIntoLine"] = \Midi\Koala\Common\TypeConverter::to_int($val);
    }

    /** 
     * @return CallFunctionArg[] 
    */ 
    public function getArgs()/* : CallFunctionArg[] */ {
        return \Midi\Koala\Common\TypeConverter::to_array($this["Args"], '\Midi\Koala\Common\TypeConverter::to_struct', array(CallFunctionArg::class,));
    }

    /** 
     * @param CallFunctionArg[] $val 
    */ 
    public function setArgs(/* CallFunctionArg[] */ $val) {
        $this["Args"] = \Midi\Koala\Common\TypeConverter::to_array($val, '\Midi\Koala\Common\TypeConverter::to_struct', array(CallFunctionArg::class,));
    }

    /** 
     * @return string 
    */ 
    public function getFuncName()/* : string */ {
        return \Midi\Koala\Common\TypeConverter::to_string($this["FuncName"]);
    }

    /** 
     * @param string $val 
    */ 
    public function setFuncName(/* string */ $val) {
        $this["FuncName"] = \Midi\Koala\Common\TypeConverter::to_string($val);
    }

    /** 
     * @return string 
    */ 
    public function getActionType()/* : string */ {
        return \Midi\Koala\Common\TypeConverter::to_string($this["ActionType"]);
    }

    /** 
     * @param string $val 
    */ 
    public function setActionType(/* string */ $val) {
        $this["ActionType"] = \Midi\Koala\Common\TypeConverter::to_string($val);
    }

    /** 
     * @return string 
    */ 
    public function getActionId()/* : string */ {
        return \Midi\Koala\Common\TypeConverter::to_string($this["ActionId"]);
    }

    /** 
     * @param string $val 
    */ 
    public function setActionId(/* string */ $val) {
        $this["ActionId"] = \Midi\Koala\Common\TypeConverter::to_string($val);
    }

    /** 
     * @return string 
    */ 
    public function getCallIntoFile()/* : string */ {
        return \Midi\Koala\Common\TypeConverter::to_string($this["CallIntoFile"]);
    }

    /** 
     * @param string $val 
    */ 
    public function setCallIntoFile(/* string */ $val) {
        $this["CallIntoFile"] = \Midi\Koala\Common\TypeConverter::to_string($val);
    }

    /** 
     * @return int 
    */ 
    public function getOccurredAt()/* : int */ {
        return \Midi\Koala\Common\TypeConverter::to_int($this["OccurredAt"]);
    }

    /** 
     * @param int $val 
    */ 
    public function setOccurredAt(/* int */ $val) {
        $this["OccurredAt"] = \Midi\Koala\Common\TypeConverter::to_int($val);
    }
}

/* THRIFT IDL
namespace php koala.replayed

union CallFunctionArg {}

struct CallFunction {
    1: string ActionId
    2: i64 OccurredAt
    3: string ActionType
    4: string CallIntoFile
    5: i64 CallIntoLine
    6: string FuncName
    7: list<CallFunctionArg> Args
}
*/